/* Generated by package_app.py. Do not edit. */
#ifdef DDND_TILED
static uint8_t *ddnd_workspace;
#define DDND_WORKSPACE_BYTES 32768
#endif
#define DDND_ARENA_BYTES 348160u
#define DDND_PAYLOAD_BYTES 46720u
#define DDND_INPUT_OFFSET 0u
#define DDND_INPUT_BYTES 20480u
#define DDND_NODE_COUNT 55
static const unsigned ddnd_payload_offsets[]={0,0,0,544,0,10016,0,19488,28960,29504,30048,30592,49536,50624,51712,52800,99520,100880,102240,103600,104960,106320,107680,136800,0,136960,136968,174728,174888,186664,0,186792,186800,205488,205616,210352,0,210416,212848,212912,0,213064,0,221512,0,224840,0,234312,0,234792,0,235624,0,240808,0};
static const unsigned ddnd_payload_bytes[]={0,544,0,9472,0,9472,0,9472,544,544,544,18944,1088,1088,1088,46720,1360,1360,1360,1360,1360,1360,29120,160,0,8,37760,160,11776,128,0,8,18688,128,4736,64,0,2432,64,152,0,8448,0,3328,0,9472,0,480,0,832,0,5184,0,64,0};
#define DDND_FIXTURE_COUNT 2
static const char *ddnd_fixture_inputs[]={"input.bin","input_gate.bin"};
static const char *ddnd_fixture_goldens[][3]={{"golden_depth_logits.bin","golden_corners.bin","golden_visibility.bin"},{"golden_gate_depth_logits.bin","golden_gate_corners.bin","golden_gate_visibility.bin"}};
#define DDND_MODEL_TAG 0x2be0691fu
static const int ddnd_output_exps[]={-4,-5,-3};
#define DDND_OUTPUT_COUNT 3
static const char *ddnd_output_files[]={"golden_depth_logits.bin","golden_corners.bin","golden_visibility.bin"};
static const unsigned ddnd_output_offsets[]={6400,960,4};
static const unsigned ddnd_output_bytes[]={20480,960,4};
static void ddnd_execute_node(int id,int8_t *a,uint8_t *w) { switch(id) {
case 1: { /* stem0 */
const ddnd_conv_params p={128,160,1,64,80,32,3,3,2,2,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+0,a+20480,(const int8_t *)(w+0),(const int32_t *)(w+288),&p,(const int32_t *)(w+416),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+0,a+20480,(const int8_t *)(w+0),(const int32_t *)(w+288),&p,(const int32_t *)(w+416));
#endif
break;}
case 2: { /* stem0.relu */
for(int j=pi_core_id();j<163840;j+=pi_cl_cluster_nb_cores()) { int8_t v=(a+20480)[j]; (a+184320)[j]=v>0?v:0; }
pi_cl_team_barrier();
break;}
case 3: { /* stem1 */
const ddnd_conv_params p={64,80,32,64,80,32,3,3,1,1,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+184320,a+0,(const int8_t *)(w+0),(const int32_t *)(w+9216),&p,(const int32_t *)(w+9344),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+184320,a+0,(const int8_t *)(w+0),(const int32_t *)(w+9216),&p,(const int32_t *)(w+9344));
#endif
break;}
case 4: { /* stem1.relu */
for(int j=pi_core_id();j<163840;j+=pi_cl_cluster_nb_cores()) { int8_t v=(a+0)[j]; (a+163840)[j]=v>0?v:0; }
pi_cl_team_barrier();
break;}
case 5: { /* stem2 */
const ddnd_conv_params p={64,80,32,64,80,32,3,3,1,1,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+163840,a+0,(const int8_t *)(w+0),(const int32_t *)(w+9216),&p,(const int32_t *)(w+9344),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+163840,a+0,(const int8_t *)(w+0),(const int32_t *)(w+9216),&p,(const int32_t *)(w+9344));
#endif
break;}
case 6: { /* stem2.relu */
for(int j=pi_core_id();j<163840;j+=pi_cl_cluster_nb_cores()) { int8_t v=(a+0)[j]; (a+163840)[j]=v>0?v:0; }
pi_cl_team_barrier();
break;}
case 7: { /* stem2 */
const ddnd_conv_params p={64,80,32,32,40,32,3,3,2,2,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+163840,a+0,(const int8_t *)(w+0),(const int32_t *)(w+9216),&p,(const int32_t *)(w+9344),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+163840,a+0,(const int8_t *)(w+0),(const int32_t *)(w+9216),&p,(const int32_t *)(w+9344));
#endif
break;}
case 8: { /* cdc0_0 */
const ddnd_conv_params p={32,40,32,32,40,32,3,3,1,1,1,1,1,1,32};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+0,a+40960,(const int8_t *)(w+0),(const int32_t *)(w+288),&p,(const int32_t *)(w+416),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+0,a+40960,(const int8_t *)(w+0),(const int32_t *)(w+288),&p,(const int32_t *)(w+416));
#endif
break;}
case 9: { /* cdc0_1 */
const ddnd_conv_params p={32,40,32,32,40,32,3,3,1,1,2,2,2,2,32};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+40960,a+0,(const int8_t *)(w+0),(const int32_t *)(w+288),&p,(const int32_t *)(w+416),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+40960,a+0,(const int8_t *)(w+0),(const int32_t *)(w+288),&p,(const int32_t *)(w+416));
#endif
break;}
case 10: { /* cdc0_2 */
const ddnd_conv_params p={32,40,32,32,40,32,3,3,1,1,3,3,3,3,32};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+0,a+40960,(const int8_t *)(w+0),(const int32_t *)(w+288),&p,(const int32_t *)(w+416),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+0,a+40960,(const int8_t *)(w+0),(const int32_t *)(w+288),&p,(const int32_t *)(w+416));
#endif
break;}
case 11: { /* down1 */
const ddnd_conv_params p={32,40,32,16,20,64,3,3,2,2,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+40960,a+0,(const int8_t *)(w+0),(const int32_t *)(w+18432),&p,(const int32_t *)(w+18688),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+40960,a+0,(const int8_t *)(w+0),(const int32_t *)(w+18432),&p,(const int32_t *)(w+18688));
#endif
break;}
case 12: { /* cdc1_0 */
const ddnd_conv_params p={16,20,64,16,20,64,3,3,1,1,1,1,1,1,64};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+0,a+20480,(const int8_t *)(w+0),(const int32_t *)(w+576),&p,(const int32_t *)(w+832),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+0,a+20480,(const int8_t *)(w+0),(const int32_t *)(w+576),&p,(const int32_t *)(w+832));
#endif
break;}
case 13: { /* cdc1_1 */
const ddnd_conv_params p={16,20,64,16,20,64,3,3,1,1,2,2,2,2,64};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+20480,a+0,(const int8_t *)(w+0),(const int32_t *)(w+576),&p,(const int32_t *)(w+832),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+20480,a+0,(const int8_t *)(w+0),(const int32_t *)(w+576),&p,(const int32_t *)(w+832));
#endif
break;}
case 14: { /* cdc1_2 */
const ddnd_conv_params p={16,20,64,16,20,64,3,3,1,1,3,3,3,3,64};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+0,a+20480,(const int8_t *)(w+0),(const int32_t *)(w+576),&p,(const int32_t *)(w+832),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+0,a+20480,(const int8_t *)(w+0),(const int32_t *)(w+576),&p,(const int32_t *)(w+832));
#endif
break;}
case 15: { /* down2 */
const ddnd_conv_params p={16,20,64,8,10,80,3,3,2,2,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+20480,a+0,(const int8_t *)(w+0),(const int32_t *)(w+46080),&p,(const int32_t *)(w+46400),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+20480,a+0,(const int8_t *)(w+0),(const int32_t *)(w+46080),&p,(const int32_t *)(w+46400));
#endif
break;}
case 16: { /* cdc2_0 */
const ddnd_conv_params p={8,10,80,8,10,80,3,3,1,1,1,1,1,1,80};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+0,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+0,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040));
#endif
break;}
case 17: { /* cdc2_1 */
const ddnd_conv_params p={8,10,80,8,10,80,3,3,1,1,2,2,2,2,80};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+6400,a+0,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+6400,a+0,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040));
#endif
break;}
case 18: { /* cdc2_2 */
const ddnd_conv_params p={8,10,80,8,10,80,3,3,1,1,3,3,3,3,80};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+0,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+0,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040));
#endif
break;}
case 19: { /* cdc2_3 */
const ddnd_conv_params p={8,10,80,8,10,80,3,3,1,1,2,2,2,2,80};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+6400,a+0,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+6400,a+0,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040));
#endif
break;}
case 20: { /* cdc2_4 */
const ddnd_conv_params p={8,10,80,8,10,80,3,3,1,1,4,4,4,4,80};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+0,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+0,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040));
#endif
break;}
case 21: { /* cdc2_5 */
const ddnd_conv_params p={8,10,80,8,10,80,3,3,1,1,6,6,6,6,80};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+6400,a+0,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+6400,a+0,(const int8_t *)(w+0),(const int32_t *)(w+720),&p,(const int32_t *)(w+1040));
#endif
break;}
case 22: { /* up2_0 */
const ddnd_conv_params p={8,10,80,8,10,40,3,3,1,1,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+0,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+28800),&p,(const int32_t *)(w+28960),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+0,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+28800),&p,(const int32_t *)(w+28960));
#endif
break;}
case 23: { /* up2_0.prelu */
ddnd_prelu_i8(a+6400,a+9600,3200,40,(const int32_t *)(w+0));
break;}
case 24: { /* resize2 */
ddnd_resize_bilinear_i8(a+9600,a+81920,8,10,16,20,40);
break;}
case 25: { /* skip2 */
const int8_t *ip[]={a+81920,a+20480};
const int channels[]={40,64};
ddnd_concat_i8(ip,a+94720,16,20,2,channels,(const int32_t *)(w+0));
break;}
case 26: { /* up2_1 */
const ddnd_conv_params p={16,20,104,16,20,40,3,3,1,1,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+94720,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+37440),&p,(const int32_t *)(w+37600),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+94720,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+37440),&p,(const int32_t *)(w+37600));
#endif
break;}
case 27: { /* up2_1.prelu */
ddnd_prelu_i8(a+6400,a+19200,12800,40,(const int32_t *)(w+0));
break;}
case 28: { /* up1_0 */
const ddnd_conv_params p={16,20,40,16,20,32,3,3,1,1,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+19200,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+11520),&p,(const int32_t *)(w+11648),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+19200,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+11520),&p,(const int32_t *)(w+11648));
#endif
break;}
case 29: { /* up1_0.prelu */
ddnd_prelu_i8(a+6400,a+16640,10240,32,(const int32_t *)(w+0));
break;}
case 30: { /* resize1 */
ddnd_resize_bilinear_i8(a+16640,a+81920,16,20,32,40,32);
break;}
case 31: { /* skip1 */
const int8_t *ip[]={a+81920,a+40960};
const int channels[]={32,32};
ddnd_concat_i8(ip,a+122880,32,40,2,channels,(const int32_t *)(w+0));
break;}
case 32: { /* up1_1 */
const ddnd_conv_params p={32,40,64,32,40,32,3,3,1,1,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+122880,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+18432),&p,(const int32_t *)(w+18560),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+122880,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+18432),&p,(const int32_t *)(w+18560));
#endif
break;}
case 33: { /* up1_1.prelu */
ddnd_prelu_i8(a+6400,a+47360,40960,32,(const int32_t *)(w+0));
break;}
case 34: { /* up0_0 */
const ddnd_conv_params p={32,40,32,32,40,16,3,3,1,1,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+47360,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+4608),&p,(const int32_t *)(w+4672),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+47360,a+6400,(const int8_t *)(w+0),(const int32_t *)(w+4608),&p,(const int32_t *)(w+4672));
#endif
break;}
case 35: { /* up0_0.prelu */
ddnd_prelu_i8(a+6400,a+26880,20480,16,(const int32_t *)(w+0));
break;}
case 36: { /* resize0 */
ddnd_resize_bilinear_i8(a+26880,a+47360,32,40,64,80,16);
break;}
case 37: { /* up0_1 */
const ddnd_conv_params p={64,80,16,64,80,16,3,3,1,1,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+47360,a+129280,(const int8_t *)(w+0),(const int32_t *)(w+2304),&p,(const int32_t *)(w+2368),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+47360,a+129280,(const int8_t *)(w+0),(const int32_t *)(w+2304),&p,(const int32_t *)(w+2368));
#endif
break;}
case 38: { /* up0_1.prelu */
ddnd_prelu_i8(a+129280,a+6400,81920,16,(const int32_t *)(w+0));
break;}
case 39: { /* disp */
const ddnd_conv_params p={64,80,16,64,80,1,3,3,1,1,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+6400,a+88320,(const int8_t *)(w+0),(const int32_t *)(w+144),&p,(const int32_t *)(w+148),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+6400,a+88320,(const int8_t *)(w+0),(const int32_t *)(w+144),&p,(const int32_t *)(w+148));
#endif
break;}
case 40: { /* depth_logits */
ddnd_resize_bilinear_i8(a+88320,a+6400,64,80,128,160,1);
break;}
case 41: { /* gate_adapter */
const ddnd_conv_params p={8,10,80,8,10,96,1,1,1,1,0,0,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+0,a+26880,(const int8_t *)(w+0),(const int32_t *)(w+7680),&p,(const int32_t *)(w+8064),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+0,a+26880,(const int8_t *)(w+0),(const int32_t *)(w+7680),&p,(const int32_t *)(w+8064));
#endif
break;}
case 42: { /* gate_adapter.relu */
for(int j=pi_core_id();j<7680;j+=pi_cl_cluster_nb_cores()) { int8_t v=(a+26880)[j]; (a+34560)[j]=v>0?v:0; }
pi_cl_team_barrier();
break;}
case 43: { /* corner0 */
const ddnd_conv_params p={8,10,96,8,10,32,1,1,1,1,0,0,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+34560,a+0,(const int8_t *)(w+0),(const int32_t *)(w+3072),&p,(const int32_t *)(w+3200),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+34560,a+0,(const int8_t *)(w+0),(const int32_t *)(w+3072),&p,(const int32_t *)(w+3200));
#endif
break;}
case 44: { /* corner0.relu */
for(int j=pi_core_id();j<2560;j+=pi_cl_cluster_nb_cores()) { int8_t v=(a+0)[j]; (a+2560)[j]=v>0?v:0; }
pi_cl_team_barrier();
break;}
case 45: { /* corner1 */
const ddnd_conv_params p={8,10,32,8,10,32,3,3,1,1,1,1,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+2560,a+0,(const int8_t *)(w+0),(const int32_t *)(w+9216),&p,(const int32_t *)(w+9344),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+2560,a+0,(const int8_t *)(w+0),(const int32_t *)(w+9216),&p,(const int32_t *)(w+9344));
#endif
break;}
case 46: { /* corner1.relu */
for(int j=pi_core_id();j<2560;j+=pi_cl_cluster_nb_cores()) { int8_t v=(a+0)[j]; (a+2560)[j]=v>0?v:0; }
pi_cl_team_barrier();
break;}
case 47: { /* corner_output */
const ddnd_conv_params p={8,10,32,8,10,12,1,1,1,1,0,0,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+2560,a+0,(const int8_t *)(w+0),(const int32_t *)(w+384),&p,(const int32_t *)(w+432),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+2560,a+0,(const int8_t *)(w+0),(const int32_t *)(w+384),&p,(const int32_t *)(w+432));
#endif
break;}
case 48: { /* corner_output.relu */
for(int j=pi_core_id();j<960;j+=pi_cl_cluster_nb_cores()) { int8_t v=(a+0)[j]; (a+960)[j]=v>0?v:0; }
pi_cl_team_barrier();
break;}
case 49: { /* visibility_compress */
const ddnd_conv_params p={8,10,96,8,10,8,1,1,1,1,0,0,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+34560,a+0,(const int8_t *)(w+0),(const int32_t *)(w+768),&p,(const int32_t *)(w+800),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+34560,a+0,(const int8_t *)(w+0),(const int32_t *)(w+768),&p,(const int32_t *)(w+800));
#endif
break;}
case 50: { /* visibility_compress.relu */
for(int j=pi_core_id();j<640;j+=pi_cl_cluster_nb_cores()) { int8_t v=(a+0)[j]; (a+1920)[j]=v>0?v:0; }
pi_cl_team_barrier();
break;}
case 51: { /* visibility_spatial */
const ddnd_conv_params p={8,10,8,1,1,8,8,10,1,1,0,0,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+1920,a+0,(const int8_t *)(w+0),(const int32_t *)(w+5120),&p,(const int32_t *)(w+5152),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+1920,a+0,(const int8_t *)(w+0),(const int32_t *)(w+5120),&p,(const int32_t *)(w+5152));
#endif
break;}
case 52: { /* visibility_spatial.relu */
for(int j=pi_core_id();j<8;j+=pi_cl_cluster_nb_cores()) { int8_t v=(a+0)[j]; (a+8)[j]=v>0?v:0; }
pi_cl_team_barrier();
break;}
case 53: { /* visibility_output */
const ddnd_conv_params p={1,1,8,1,1,4,1,1,1,1,0,0,1,1,1};
#ifdef DDND_TILED
ddnd_conv_i8_ohwi_tiled(a+8,a+0,(const int8_t *)(w+0),(const int32_t *)(w+32),&p,(const int32_t *)(w+48),ddnd_workspace,DDND_WORKSPACE_BYTES);
#else
ddnd_conv_i8_ohwi(a+8,a+0,(const int8_t *)(w+0),(const int32_t *)(w+32),&p,(const int32_t *)(w+48));
#endif
break;}
case 54: { /* visibility_output.relu */
for(int j=pi_core_id();j<4;j+=pi_cl_cluster_nb_cores()) { int8_t v=(a+0)[j]; (a+4)[j]=v>0?v:0; }
pi_cl_team_barrier();
break;}
default: break; }}
