# Generated dual STDC DORY package.
CORE ?= 7
FLASH_TYPE ?= HYPERFLASH
RAM_TYPE ?= HYPERRAM
APP_SRCS += $(wildcard $(NETWORK_DIR)/src/*.c)
APP_CFLAGS += -I$(NETWORK_DIR)/inc
APP_CFLAGS += -DNUM_CORES=$(CORE) -DGAP8_MULTITASK_NETWORK=1
APP_CFLAGS += -DGAP8_STDC_PAIR_NETWORK=1
APP_CFLAGS += -Wno-error -O2 -fno-indirect-inlining -flto
APP_LDFLAGS += -lm -flto
APP_CFLAGS += -DGAP_SDK=1 -DFLASH_TYPE=$(FLASH_TYPE)
APP_CFLAGS += -DUSE_$(FLASH_TYPE) -DUSE_$(RAM_TYPE)
APP_CFLAGS += -DALWAYS_BLOCK_DMA_TRANSFERS -DFS_READ_FS
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution0_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution11_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution12_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution13_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution1_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution2_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution3_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution4_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution5_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution6_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution8_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_corner_BNReluConvolution9_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution0_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution11_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution12_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution13_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution14_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution16_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution17_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution19_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution1_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution20_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution22_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution23_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution24_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution25_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution27_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution28_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution2_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution30_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution31_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution33_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution34_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution36_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution37_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution39_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution3_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution40_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution42_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution43_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution45_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution4_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution5_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution6_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution8_weights.hex
FLASH_FILES += $(NETWORK_DIR)/hex/stdc_danger_BNReluConvolution9_weights.hex
READFS_FILES += $(FLASH_FILES)
