#!/usr/bin/env python3
"""Package the calibrated integer graph into an AutoTiler-free PMSIS app."""
import argparse, hashlib, json, math, shutil
from pathlib import Path

PARAMS = "ih iw ic oh ow oc kh kw sy sx py px dy dx groups".split()

def package(export: Path, app: Path):
    graph=json.loads((export/"graph.json").read_text())
    nodes=graph["nodes"]
    for i,n in enumerate(nodes): n.setdefault("id",i)
    assert [n["id"] for n in nodes]==list(range(len(nodes))), "Dense node IDs required"
    assert nodes[0]["op"]=="input"
    blob=(export/"weights.bin").read_bytes()
    payloads=[]
    for n in nodes:
        fields=[]
        if n["op"]=="conv":
            fields=[("weights_offset",n["weights_bytes"]),("bias_offset",4*n["shape"][2]),("shifts_offset",4*n["shape"][2])]
        elif n["op"]=="prelu": fields=[("slope_offset",4*n["shape"][2])]
        elif n["op"]=="concat": fields=[("shifts_offset",4*len(n["inputs"]))]
        if fields:
            lo=min(n[key] for key,size in fields)
            hi=max(n[key]+size for key,size in fields)
            assert lo%4==0, ("payload must be aligned",n["id"])
            assert 0<=lo<=hi<=len(blob)
            payloads.append((lo,hi-lo))
        else: payloads.append((0,0))
    arena=graph["arena_bytes"]
    for n in nodes:
        assert n["offset"]>=0 and n["offset"]+math.prod(n["shape"])<=arena
        for inp in n.get("inputs",[]): assert inp<n["id"]
    lines=["/* Generated by package_app.py. Do not edit. */",
           "#ifdef DDND_TILED",
           "static uint8_t *ddnd_workspace;",
           "#define DDND_WORKSPACE_BYTES 32768",
           "#endif",
           f"#define DDND_ARENA_BYTES {arena}u",
           f"#define DDND_PAYLOAD_BYTES {max(size for _,size in payloads)}u",
           f"#define DDND_INPUT_OFFSET {nodes[0]['offset']}u",
           f"#define DDND_INPUT_BYTES {math.prod(nodes[0]['shape'])}u",
           f"#define DDND_NODE_COUNT {len(nodes)}",
           "static const unsigned ddnd_payload_offsets[]={"+",".join(str(o) for o,b in payloads)+"};",
           "static const unsigned ddnd_payload_bytes[]={"+",".join(str(b) for o,b in payloads)+"};"]
    outputs=graph["outputs"]
    fixtures=[{"input":"input.bin","goldens":["golden_"+k+".bin" for k in outputs]}]
    gate_files=["input_gate.bin"]+["golden_gate_"+k+".bin" for k in outputs]
    gate_present=[(export/f).exists() for f in gate_files]
    if any(gate_present):
        assert all(gate_present), "Incomplete gate fixture"
        fixtures.append({"input":gate_files[0],"goldens":gate_files[1:]})
    lines += [f"#define DDND_FIXTURE_COUNT {len(fixtures)}",
              "static const char *ddnd_fixture_inputs[]={"+",".join(json.dumps(f["input"]) for f in fixtures)+"};",
              "static const char *ddnd_fixture_goldens[][3]={"+",".join("{"+",".join(json.dumps(n) for n in f["goldens"])+"}" for f in fixtures)+"};"]
    lines += [f"#define DDND_MODEL_TAG 0x{hashlib.sha256(blob).hexdigest()[:8]}u",
              "static const int ddnd_output_exps[]={"+",".join(str(nodes[v]["scale_exp"]) for v in outputs.values())+"};",
              f"#define DDND_OUTPUT_COUNT {len(outputs)}",
              "static const char *ddnd_output_files[]={"+",".join(json.dumps("golden_"+k+".bin") for k in outputs)+"};",
              "static const unsigned ddnd_output_offsets[]={"+",".join(str(nodes[v]["offset"]) for v in outputs.values())+"};",
              "static const unsigned ddnd_output_bytes[]={"+",".join(str(math.prod(nodes[v]["shape"])) for v in outputs.values())+"};",
              "static void ddnd_execute_node(int id,int8_t *a,uint8_t *w) { switch(id) {"]
    for n in nodes[1:]:
        idx=n["id"]; op=n["op"]; ins=n["inputs"]; out=f"a+{n['offset']}"
        inp=f"a+{nodes[ins[0]]['offset']}"
        lo=payloads[idx][0]
        ptr=lambda key,typ: f"(const {typ} *)(w+{n[key]-lo})"
        lines.append(f"case {idx}: {{ /* {n['name']} */")
        if op=="conv":
            p=n.get("params",n)
            kernel="ddnd_conv_i8_ohwi" if n.get("weights_layout",n.get("weight_layout"))=="OHWI" else "ddnd_conv_i8"
            lines += ["const ddnd_conv_params p={"+",".join(str(p[k]) for k in PARAMS)+"};",
                      f"{kernel}({inp},{out},{ptr('weights_offset','int8_t')},{ptr('bias_offset','int32_t')},&p,{ptr('shifts_offset','int32_t')});"]
            if kernel=="ddnd_conv_i8_ohwi":
                call=lines.pop()
                tiled=call.replace("ddnd_conv_i8_ohwi(", "ddnd_conv_i8_ohwi_tiled(").replace(");",",ddnd_workspace,DDND_WORKSPACE_BYTES);")
                lines += ["#ifdef DDND_TILED",tiled,"#else",call,"#endif"]
        elif op=="prelu":
            lines += [f"ddnd_prelu_i8({inp},{out},{math.prod(n['shape'])},{n['shape'][2]},{ptr('slope_offset','int32_t')});"]
        elif op=="relu":
            assert n["scale_exp"]==nodes[ins[0]]["scale_exp"], "ReLU rescale unsupported"
            lines += [f"for(int j=pi_core_id();j<{math.prod(n['shape'])};j+=pi_cl_cluster_nb_cores()) {{ int8_t v=({inp})[j]; ({out})[j]=v>0?v:0; }}","pi_cl_team_barrier();"]
        elif op=="resize":
            sh=nodes[ins[0]]["shape"]; oh,ow,oc=n["shape"]
            assert sh[2]==oc and n["scale_exp"]==nodes[ins[0]]["scale_exp"]
            lines += [f"ddnd_resize_bilinear_i8({inp},{out},{sh[0]},{sh[1]},{oh},{ow},{oc});"]
        elif op=="concat":
            lines += ["const int8_t *ip[]={"+",".join(f"a+{nodes[i]['offset']}" for i in ins)+"};",
                      "const int channels[]={"+",".join(str(nodes[i]["shape"][2]) for i in ins)+"};",
                      f"ddnd_concat_i8(ip,{out},{n['shape'][0]},{n['shape'][1]},{len(ins)},channels,{ptr('shifts_offset','int32_t')});"]
        else: raise ValueError(f"Unsupported op {op}")
        lines += ["break;}"]
    lines += ['default: break; }}']
    (app/"inc").mkdir(parents=True,exist_ok=True)
    (app/"hex").mkdir(parents=True,exist_ok=True)
    (app/"inc/graph.h").write_text("\n".join(lines)+"\n")
    files=["weights.bin"]+[name for f in fixtures for name in [f["input"]]+f["goldens"]]
    for filename in files: shutil.copyfile(export/filename,app/"hex"/filename)
    metadata={"export":str(export.resolve()),"fixtures":fixtures,"arena_bytes":arena,
              "max_payload_bytes":max(b for _,b in payloads),"nodes":len(nodes),
              "files":{f:hashlib.sha256((export/f).read_bytes()).hexdigest() for f in files},
              "integer_outputs":"raw logits, no output activation omitted from mathematical inference; sigmoid performed downstream"}
    (app/"manifest.json").write_text(json.dumps(metadata,indent=2)+"\n")
    print(json.dumps(metadata,indent=2))
if __name__=="__main__":
    p=argparse.ArgumentParser()
    p.add_argument("--export",type=Path,default=Path(__file__).parent/"artifacts/export")
    p.add_argument("--app",type=Path,default=Path(__file__).parent/"gap8_app")
    a=p.parse_args();package(a.export,a.app)

